[build]
  command = "npm run build"
  publish = "build"

# Serve static assets directly
[[redirects]]
  from = "/audio/*"
  to = "/audio/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/favicon.png"
  to = "/favicon.png"
  status = 200

# All other routes go to SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 